version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install dep
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - run:
          name: deploy app
          command: npm run deploy
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - .
#   deploy: # this can be any name you choose
#     docker:
#       - image: cimg/node:17.2.0
#     steps:
#       - attach_workspace:
#           at: ~/project
#       - heroku/deploy-via-git: 
#           force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

# workflows:
#   on_commit:
#     jobs:
#       - build_and_test
#       # Follow instructions here to authenticate git for Heroku: https://devcenter.heroku.com/articles/git#http-git-authentication
#       # The following code may be uncommented, onnce HEROKU_API_KEY & HEROKU_APP_NAME environemnt variables are present
#       # Read more: https://circleci.com/docs/2.0/env-vars/
#       # - deploy:
#       #     requires:
#       #       - build_and_test # only deploy if the build_and_test job has completed
#       #     filters:
#       #       branches:
#       #         only: master # only deploy when on main/master
#   nightly:
#     triggers:
#       - schedule:
#           cron: "0 0 * * *"       
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - build_and_test
#       # Follow instructions here to authenticate git for Heroku: https://devcenter.heroku.com/articles/git#http-git-authentication
#       # The following code may be uncommented, onnce HEROKU_API_KEY & HEROKU_APP_NAME environemnt variables are present
#       # Read more: https://circleci.com/docs/2.0/env-vars/
#       # - deploy:
#       #     requires:
#       #       - build_and_test # only deploy if the build_and_test job has completed
#       #     filters:
#       #       branches:
#       #         only: master # only deploy when on main/master